name: Billing Alert
on:
#  schedule:
#    - cron: "5 */6 * * *"
  push:
    tags-ignore:
      - '*'
    branches:
      - master

jobs:
  alert:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    runs-on: ubuntu-latest

    steps:
    - name: Billing Alert
      uses: dylanninin/vultr-billing-alert@master
      id: billing
      with:
        vultr_api_account: ${{ secrets.VULTR_API_ACCOUNT }}
        vultr_api_key: ${{ secrets.VULTR_API_KEY }}
        slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

    - name: Echo output
      run: |
        echo "traffic ${{ steps.billing.outputs.vultr_traffic }}"
        echo "charge ${{ steps.billing.outputs.vultr_charge }}"
