name: Billing Alert
on:
#  schedule:
#    - cron: "5 */6 * * *"
  push:
    tags-ignore:
      - '*'
    branches:
      - master

jobs:
  alert:
    name: billing alert
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    runs-on: ubuntu-latest

    steps:
    - name: Billing Alert
      uses: dylanninin/vultr-billing-alert@master
      id: vultr-billing-alert
      with:
        vultr_api_account: ${{ secrets.VULTR_API_ACCOUNT }}
        vultr_api_key: ${{ secrets.VULTR_API_KEY }}
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
